"""
Blender script emitter.

This module does not import bpy. It emits a self-contained Blender Python
script that can be run inside Blender after the ASCII dry run passes.

The generated script includes placeholders for more advanced craft operations
like true flute booleans and entasis mesh shaping. The current output creates
named primitives, applies dimensions, assigns simple stone materials, and
adds bevels to keep the test asset readable.
"""

from __future__ import annotations

from .ops import AddBox, AddCylinder, AddRing, CutFlutes, AddLabel, BuildOp


class BlenderBackend:
    def emit(self, ops: list[BuildOp]) -> str:
        lines: list[str] = []
        lines += [
            "# Generated by ascii_blender_dryrun_v0.",
            "# Recipe is truth. ASCII preview is proof. Blender script is execution.",
            "import bpy",
            "import math",
            "from mathutils import Vector",
            "",
            "bpy.ops.object.select_all(action='SELECT')",
            "bpy.ops.object.delete()",
            "",
            "def make_mat(name, color):",
            "    mat = bpy.data.materials.new(name)",
            "    mat.diffuse_color = color",
            "    return mat",
            "",
            "MATS = {",
            "    'stone': make_mat('aged_warm_limestone', (0.72, 0.68, 0.60, 1.0)),",
            "    'limestone': make_mat('light_limestone', (0.80, 0.78, 0.70, 1.0)),",
            "}",
            "",
            "def assign_mat(obj, key):",
            "    obj.data.materials.append(MATS.get(key, MATS['stone']))",
            "",
            "def bevel(obj, amount=0.06, segments=2):",
            "    mod = obj.modifiers.new('soft_test_bevel', 'BEVEL')",
            "    mod.width = amount",
            "    mod.segments = segments",
            "    mod.affect = 'EDGES'",
            "    obj.modifiers.new('weighted_normals', 'WEIGHTED_NORMAL')",
            "",
            "def add_box(name, width, depth, height, loc, material):",
            "    bpy.ops.mesh.primitive_cube_add(size=1, location=loc)",
            "    obj = bpy.context.object",
            "    obj.name = name",
            "    obj.dimensions = (width, depth, height)",
            "    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)",
            "    assign_mat(obj, material)",
            "    bevel(obj, 0.04, 1)",
            "    return obj",
            "",
            "def add_cylinder(name, radius, height, loc, vertices, material):",
            "    bpy.ops.mesh.primitive_cylinder_add(vertices=vertices, radius=radius, depth=height, location=loc)",
            "    obj = bpy.context.object",
            "    obj.name = name",
            "    assign_mat(obj, material)",
            "    bevel(obj, 0.035, 1)",
            "    return obj",
            "",
            "def add_tapered_cylinder(name, radius, top_radius, height, loc, vertices, material, entasis=False, rings=24):",
            "    verts = []",
            "    faces = []",
            "    rings = max(2, int(rings))",
            "    vertices = max(4, int(vertices))",
            "    for ring in range(rings + 1):",
            "        t = ring / rings",
            "        z = -height * 0.5 + height * t",
            "        linear_radius = radius + (top_radius - radius) * t",
            "        bulge = math.sin(math.pi * t) * radius * 0.045 if entasis else 0.0",
            "        rr = max(0.001, linear_radius + bulge)",
            "        for index in range(vertices):",
            "            angle = math.tau * index / vertices",
            "            verts.append((math.cos(angle) * rr, math.sin(angle) * rr, z))",
            "    for ring in range(rings):",
            "        current = ring * vertices",
            "        next_ring = (ring + 1) * vertices",
            "        for index in range(vertices):",
            "            nxt = (index + 1) % vertices",
            "            faces.append([current + index, current + nxt, next_ring + nxt, next_ring + index])",
            "    faces.append(list(range(vertices - 1, -1, -1)))",
            "    top_start = rings * vertices",
            "    faces.append(list(range(top_start, top_start + vertices)))",
            "    mesh = bpy.data.meshes.new(name + '_mesh')",
            "    mesh.from_pydata(verts, [], faces)",
            "    mesh.update(calc_edges=True)",
            "    obj = bpy.data.objects.new(name, mesh)",
            "    bpy.context.collection.objects.link(obj)",
            "    obj.location = loc",
            "    assign_mat(obj, material)",
            "    bevel(obj, 0.035, 1)",
            "    return obj",
            "",
            "def add_ring(name, radius, tube_height, loc, vertices, material):",
            "    obj = add_cylinder(name, radius, tube_height, loc, vertices, material)",
            "    return obj",
            "",
            "def cut_flutes(target_name, count, depth, width_ratio, start_z, end_z):",
            "    target = bpy.data.objects.get(target_name)",
            "    if target is None:",
            "        print(f'Flute target not found: {target_name}')",
            "        return",
            "    count = max(1, int(count))",
            "    radius = max(target.dimensions.x, target.dimensions.y) * 0.5",
            "    cutter_radius = max(0.02, radius * width_ratio * 0.5)",
            "    cutter_offset = max(0.001, radius + cutter_radius - depth)",
            "    z0 = target.location.z - target.dimensions.z * 0.5 if start_z is None else float(start_z)",
            "    z1 = target.location.z + target.dimensions.z * 0.5 if end_z is None else float(end_z)",
            "    cutter_depth = max(0.001, z1 - z0)",
            "    z_mid = (z0 + z1) * 0.5",
            "    for index in range(count):",
            "        angle = math.tau * index / count",
            "        loc = (math.cos(angle) * cutter_offset, math.sin(angle) * cutter_offset, z_mid)",
            "        bpy.ops.mesh.primitive_cylinder_add(vertices=18, radius=cutter_radius, depth=cutter_depth, location=loc)",
            "        cutter = bpy.context.object",
            "        cutter.name = f'{target_name}.flute_cutter_{index:02d}'",
            "        mod = target.modifiers.new(name=f'flute_cut_{index:02d}', type='BOOLEAN')",
            "        mod.operation = 'DIFFERENCE'",
            "        if hasattr(mod, 'solver'):",
            "            mod.solver = 'EXACT'",
            "        mod.object = cutter",
            "        bpy.ops.object.select_all(action='DESELECT')",
            "        target.select_set(True)",
            "        bpy.context.view_layer.objects.active = target",
            "        try:",
            "            bpy.ops.object.modifier_apply(modifier=mod.name)",
            "        except Exception as exc:",
            "            print(f'Failed to apply {mod.name}: {exc}')",
            "            target.modifiers.remove(mod)",
            "        bpy.data.objects.remove(cutter, do_unlink=True)",
            "",
        ]

        for op in ops:
            if isinstance(op, AddBox):
                lines.append(
                    f"add_box({op.name!r}, {op.width}, {op.depth}, {op.height}, ({op.x}, {op.y}, {op.z}), {op.material!r})"
                )
            elif isinstance(op, AddCylinder):
                top_radius = op.taper_top_radius or op.radius
                if op.taper_top_radius is not None or op.entasis:
                    lines.append(
                        f"obj = add_tapered_cylinder({op.name!r}, {op.radius}, {top_radius}, {op.height}, ({op.x}, {op.y}, {op.z}), {op.vertices}, {op.material!r}, entasis={op.entasis})"
                    )
                else:
                    lines.append(
                        f"obj = add_cylinder({op.name!r}, {op.radius}, {op.height}, ({op.x}, {op.y}, {op.z}), {op.vertices}, {op.material!r})"
                    )
            elif isinstance(op, AddRing):
                radius = op.radius + op.overhang
                lines.append(
                    f"add_ring({op.name!r}, {radius}, {op.tube_height}, ({op.x}, {op.y}, {op.z}), {op.vertices}, {op.material!r})"
                )
            elif isinstance(op, CutFlutes):
                lines.append(
                    f"cut_flutes({op.target!r}, {op.count}, {op.depth}, {op.width_ratio}, {op.start_z!r}, {op.end_z!r})"
                )
            elif isinstance(op, AddLabel):
                lines += [
                    f"# LABEL {op.name}: {op.text}",
                ]

        lines += [
            "",
            "# Camera and light for quick visual check.",
            "bpy.ops.object.light_add(type='AREA', location=(0, -35, 75))",
            "light = bpy.context.object",
            "light.name = 'preview_key_area_light'",
            "light.data.energy = 450",
            "light.data.size = 5",
            "",
            "bpy.ops.object.camera_add(location=(0, -90, 42), rotation=(math.radians(65), 0, 0))",
            "bpy.context.scene.camera = bpy.context.object",
            "",
            "print('Generated Doric dry-run column script executed.')",
        ]
        return "\n".join(lines) + "\n"
