"""
Blender script emitter.

This module does not import bpy. It emits a self-contained Blender Python
script that can be run inside Blender after the ASCII dry run passes.

The generated script includes placeholders for more advanced craft operations
like true flute booleans and entasis mesh shaping. The current output creates
named primitives, applies dimensions, assigns simple stone materials, and
adds bevels to keep the test asset readable.
"""

from __future__ import annotations

from .ops import AddBox, AddCylinder, AddRing, CutFlutes, AddLabel, BuildOp


class BlenderBackend:
    def emit(self, ops: list[BuildOp]) -> str:
        lines: list[str] = []
        lines += [
            "# Generated by ascii_blender_dryrun_v0.",
            "# Recipe is truth. ASCII preview is proof. Blender script is execution.",
            "import bpy",
            "import math",
            "from mathutils import Vector",
            "",
            "bpy.ops.object.select_all(action='SELECT')",
            "bpy.ops.object.delete()",
            "",
            "def make_mat(name, color):",
            "    mat = bpy.data.materials.new(name)",
            "    mat.diffuse_color = color",
            "    return mat",
            "",
            "MATS = {",
            "    'stone': make_mat('aged_warm_limestone', (0.72, 0.68, 0.60, 1.0)),",
            "    'limestone': make_mat('light_limestone', (0.80, 0.78, 0.70, 1.0)),",
            "}",
            "",
            "def assign_mat(obj, key):",
            "    obj.data.materials.append(MATS.get(key, MATS['stone']))",
            "",
            "def bevel(obj, amount=0.06, segments=2):",
            "    mod = obj.modifiers.new('soft_test_bevel', 'BEVEL')",
            "    mod.width = amount",
            "    mod.segments = segments",
            "    mod.affect = 'EDGES'",
            "    obj.modifiers.new('weighted_normals', 'WEIGHTED_NORMAL')",
            "",
            "def add_box(name, width, depth, height, loc, material):",
            "    bpy.ops.mesh.primitive_cube_add(size=1, location=loc)",
            "    obj = bpy.context.object",
            "    obj.name = name",
            "    obj.dimensions = (width, depth, height)",
            "    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)",
            "    assign_mat(obj, material)",
            "    bevel(obj, 0.04, 1)",
            "    return obj",
            "",
            "def add_cylinder(name, radius, height, loc, vertices, material):",
            "    bpy.ops.mesh.primitive_cylinder_add(vertices=vertices, radius=radius, depth=height, location=loc)",
            "    obj = bpy.context.object",
            "    obj.name = name",
            "    assign_mat(obj, material)",
            "    bevel(obj, 0.035, 1)",
            "    return obj",
            "",
            "def add_ring(name, radius, tube_height, loc, vertices, material):",
            "    obj = add_cylinder(name, radius, tube_height, loc, vertices, material)",
            "    return obj",
            "",
        ]

        for op in ops:
            if isinstance(op, AddBox):
                lines.append(
                    f"add_box({op.name!r}, {op.width}, {op.depth}, {op.height}, ({op.x}, {op.y}, {op.z}), {op.material!r})"
                )
            elif isinstance(op, AddCylinder):
                lines.append(
                    f"obj = add_cylinder({op.name!r}, {op.radius}, {op.height}, ({op.x}, {op.y}, {op.z}), {op.vertices}, {op.material!r})"
                )
                if op.taper_top_radius is not None:
                    lines += [
                        f"# TODO: taper {op.name} top radius to {op.taper_top_radius}.",
                        "# Current v0 emits a straight cylinder so ASCII/backend contract can stabilize first.",
                    ]
                if op.entasis:
                    lines += [
                        f"# TODO: apply entasis curve to {op.name}.",
                    ]
            elif isinstance(op, AddRing):
                radius = op.radius + op.overhang
                lines.append(
                    f"add_ring({op.name!r}, {radius}, {op.tube_height}, ({op.x}, {op.y}, {op.z}), {op.vertices}, {op.material!r})"
                )
            elif isinstance(op, CutFlutes):
                lines += [
                    f"# TODO: cut {op.count} radial flutes into {op.target}.",
                    f"# flute depth={op.depth}, width_ratio={op.width_ratio}, z_range=({op.start_z}, {op.end_z})",
                    "# Planned implementation: create one vertical rounded cutter, radial-array it, then boolean difference.",
                ]
            elif isinstance(op, AddLabel):
                lines += [
                    f"# LABEL {op.name}: {op.text}",
                ]

        lines += [
            "",
            "# Camera and light for quick visual check.",
            "bpy.ops.object.light_add(type='AREA', location=(0, -35, 75))",
            "light = bpy.context.object",
            "light.name = 'preview_key_area_light'",
            "light.data.energy = 450",
            "light.data.size = 5",
            "",
            "bpy.ops.object.camera_add(location=(0, -90, 42), rotation=(math.radians(65), 0, 0))",
            "bpy.context.scene.camera = bpy.context.object",
            "",
            "print('Generated Doric dry-run column script executed.')",
        ]
        return "\n".join(lines) + "\n"
